name: "Calculator Scenario 01"

on:
  push:
    branches: [ "main" ]
    paths: [ 'Calculator/**', '.github/workflows/calculator-1.yml' ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Calculator/Calculator.Core.Tests
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --collect "Code Coverage" --results-directory TestResults --no-build --verbosity normal

    - name: Install dotnet-coverage
      run: dotnet tool install -g dotnet-coverage

    - name: Convert .coverage report to Cobertura
      run: dotnet-coverage merge TestResults/*.coverage -f cobertura -o report.cobertura.xml

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
      with:
        reports: 'report.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'MarkdownSummaryGithub'

    - name: Upload coverage into summary
      run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: TestResults/*.coverage
