name: "Calculator Scenario 01"

on:
  push:
    branches: [ "main" ]
    paths: [ 'Calculator/**', '.github/workflows/calculator-1.yml' ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Calculator/Calculator.Core.Tests
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run Tests with Code Coverage
      run: dotnet test --collect:"XPlat Code Coverage" --results-directory TestResults --no-build --verbosity normal

    - name: Verify Coverage Files
      run: ls -R TestResults

    - name: Convert .coverage to Cobertura
      run: |
        if [ -f "TestResults/**/coverage.cobertura.xml" ]; then
          mv TestResults/coverage.cobertura.xml report.cobertura.xml
        else
          echo "Error: Cobertura report not found!"
          exit 1
        fi

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
      with:
        reports: 'report.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'MarkdownSummaryGithub'

    - name: Upload coverage into summary
      run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: TestResults/*.coverage
