name: "Calculator Scenario 02"

on:
  push:
    branches: [ "main" ]
    paths: [ 'Calculator/**',  '.github/workflows/calculator-2.yml' ]

env:
  WORKING_DIR_TESTS: ./Calculator/Calculator.Server.Tests
  WORKING_DIR_SERVER: ./Calculator/Calculator.Core

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR_TESTS }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --collect "Code Coverage;Format=cobertura" --no-build --verbosity normal

    - name: Check if coverage files exist
      run: ls -R TestResults

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
      with:
        reports: './**/TestResults/**/*.cobertura.xml'
        targetdir: '${{ github.workspace }}/coveragereport'
        reporttypes: 'MarkdownSummaryGithub'

    - name: Upload coverage into summary
      run: cat $GITHUB_WORKSPACE/coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
      
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ./**/TestResults/**/*.cobertura.xml

  publish:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR_SERVER }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish
      run: dotnet publish -c Release -o ${{ github.workspace }}/published-app

    - name: Upload published application
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ${{ github.workspace }}/published-app
